var files_dup =
[
    [ "antenna.cpp", "antenna_8cpp.html", null ],
    [ "antenna.h", "antenna_8h.html", "antenna_8h" ],
    [ "ax.cpp", "ax_8cpp.html", "ax_8cpp" ],
    [ "ax.h", "ax_8h.html", "ax_8h" ],
    [ "ax_fifo.h", "ax__fifo_8h.html", "ax__fifo_8h" ],
    [ "ax_hw.cpp", "ax__hw_8cpp.html", "ax__hw_8cpp" ],
    [ "ax_hw.h", "ax__hw_8h.html", "ax__hw_8h" ],
    [ "ax_modes.cpp", "ax__modes_8cpp.html", "ax__modes_8cpp" ],
    [ "ax_modes.h", "ax__modes_8h.html", "ax__modes_8h" ],
    [ "ax_params.cpp", "ax__params_8cpp.html", "ax__params_8cpp" ],
    [ "ax_params.h", "ax__params_8h.html", "ax__params_8h" ],
    [ "ax_reg.h", "ax__reg_8h.html", null ],
    [ "ax_reg_values.h", "ax__reg__values_8h.html", null ],
    [ "ax_structures.h", "ax__structures_8h.html", "ax__structures_8h" ],
    [ "beacon.cpp", "beacon_8cpp.html", "beacon_8cpp" ],
    [ "beacon.h", "beacon_8h.html", "beacon_8h" ],
    [ "commands.cpp", "commands_8cpp.html", null ],
    [ "commands.h", "commands_8h.html", "commands_8h" ],
    [ "constants.cpp", "constants_8cpp.html", null ],
    [ "constants.h", "constants_8h.html", null ],
    [ "efuse.cpp", "efuse_8cpp.html", null ],
    [ "efuse.h", "efuse_8h.html", "efuse_8h" ],
    [ "ExternalWatchdog.cpp", "_external_watchdog_8cpp.html", null ],
    [ "ExternalWatchdog.h", "_external_watchdog_8h.html", "_external_watchdog_8h" ],
    [ "fec.cpp", "fec_8cpp.html", "fec_8cpp" ],
    [ "fec.h", "fec_8h.html", "fec_8h" ],
    [ "KISS.cpp", "_k_i_s_s_8cpp.html", null ],
    [ "KISS.h", "_k_i_s_s_8h.html", null ],
    [ "packetfinder.h", "packetfinder_8h.html", null ],
    [ "radio.cpp", "radio_8cpp.html", null ],
    [ "radio.h", "radio_8h.html", "radio_8h" ],
    [ "testing_support.cpp", "testing__support_8cpp.html", null ],
    [ "testing_support.h", "testing__support_8h.html", null ]
];